<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>PleOps.Moxmi</AssemblyName>
    <Description>Library for the standard MOXMI mod installer format.</Description>
    <IsPackable>true</IsPackable>

    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>

    <RootNamespace>PleOps.Moxmi</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../docs/images/logo_128.png" Pack="true" PackagePath="$(PackageIcon)" Visible="false" />
    <None Include="../../docs/index.md" Pack="true" PackagePath="$(PackageReadmeFile)" Visible="False" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="Yarhl" Version="4.0.0" />
  </ItemGroup>
</Project>
