name: Build and release

on:
  # Dev
  workflow_dispatch:
  pull_request:
  push:
    # Preview
    branches: [ main ]
    # Stable
    tags: [ "v*" ]

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yml
    with:
      dotnet_version: '8.0.303'

  # Preview release on push to main only
  # Stable release on version tag push only
  deploy:
    name: "Deploy"
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      dotnet_version: '8.0.303'
